### ISSUE TITLE
Automate github action to push images to GCR

### ISSUE THREAD

**Issue by chuckha** [kubernetes-sigs/cluster-api-provider-docker#117]
/kind feature

**Describe the solution you'd like**
I would like GitHub actions to push images to GCR. It is not very straightforward. If you look at some of the history on the .github/main.workflow file you will see many attempts were made.

Ideally this will tie into the image promoter process.

**Anything else you would like to add:**
I would strongly suggest having an alternative repo where you can experiment on that has access to GitHub actions as iterating in *this* repo is extremely slow due to the review process required.

**Comment by dennisme** [comment]
Im on the beta for github actions :(, is there any other way I can iterate on this? If so I'd be willing to pick this one up @chuckha.

**Comment by chuckha** [comment]
I think this is the wrong approach and this ticket should actually use the k8s image promoter process. I'm going to make a new issue and close this one out
