### ISSUE TITLE
Documentation Clarification :  what does REGISTRY mean

### ISSUE THREAD

**Issue by sb1975** [kubernetes-sigs/cluster-api-provider-docker#132]
/kind feature

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]

so for this step - REGISTRY=<MY_REGISTRY> ./scripts/publish-manager.sh

sudeepbatra  < 1 minute ago
what does REGISTRY mean ? is it the Docker Registry or I need to create my local docker registry ?

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api-provider-docker version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by detiber** [comment]
@sb1975 REGISTRY is meant to be any pre-existing container registry. This could be a Docker Hub registry, a gcr.io bucket, or any other container registry that you have access configured (through the Docker config) to push images to.
