### ISSUE TITLE
Actuator/controller

### ISSUE THREAD

**Issue by amy** [kubernetes-sigs/cluster-api-provider-docker#136]
Update the controller logic to remove actuator in favor of the `DockerMachineController`. Much of this will involve filling out the `Reconcile` function. This may also include updating the CRDs in the `infrastructure.x-k8s.io` group. It would be great to flesh this out and keep things like the version of the kind node inside, but that's TBD. Definitely up for discussion here.

Related to: https://github.com/kubernetes-sigs/cluster-api-provider-docker/issues/54

**Comment by chuckha** [comment]
this got merged

/close
