### ISSUE TITLE
Add a DockerCluster type

### ISSUE THREAD

**Issue by chuckha** [kubernetes-sigs/cluster-api-provider-docker#137]
/kind feature

**Describe the solution you'd like**
In line with the AWSCluster object, we will also need a docker specific cluster object. We may not use any fields in it, but it should follow v1alpha1.Machine.ProviderSpec => Infrastructure ProviderMachine

as in, v1alpha1.Cluster.ProviderSpec => InfrastructureProviderCluster

please use Kubebuilder v0.2.0-beta.4 or newer to generate this code

/priority important-soon

**Comment by ericzhang08** [comment]
@chuckha  could I work on this issue?

**Comment by chuckha** [comment]
@ericzhang08 yes!

/assign @ericzhang08 
/lifecycle active

**Comment by ericzhang08** [comment]
Hi, @chuckha. What do you mean  "it should follow v1alpha1.Machine.ProviderSpec => Infrastructure ProviderMachine".
