### ISSUE TITLE
Change the Update in Reconcile() to a Patch

### ISSUE THREAD

**Issue by amy** [kubernetes-sigs/cluster-api-provider-docker#151]
https://github.com/kubernetes-sigs/cluster-api-provider-docker/pull/148#discussion_r310257842

`r.Client.Update(...)` is used within `controllers/dockermachine_controller.go` in `Reconcile(...)`. Change that to a `Patch`.

**Comment by chuckha** [comment]
/priority important-soon
/good-first-issue

Happy to help any newcomers get through this one!
