### ISSUE TITLE
Error Logging Strategy

### ISSUE THREAD

**Issue by amy** [kubernetes-sigs/cluster-api-provider-docker#153]
This ties into a larger theme of needing an overall logging strategy. See the original issue in the kubeadm bootstrapper for more detail: https://github.com/kubernetes-sigs/cluster-api-bootstrap-provider-kubeadm/issues/65

Also related: https://github.com/kubernetes-sigs/cluster-api-provider-docker/pull/148/files#r310253386

Ex: within `Reconcile()` we see `return ctrl.Result{}, err`. Should these be wrapped or should we print stack traces.

**Comment by amy** [comment]
Also something that may be useful: https://github.com/kubernetes-sigs/cluster-api-provider-docker/pull/148/files#r310262931

**Comment by chuckha** [comment]
dupe of #224 
/close
