### ISSUE TITLE
Track and document external dependencies

### ISSUE THREAD

**Issue by amy** [kubernetes-sigs/cluster-api-provider-docker#19]
Ex: `kind` tool needs to have a version >= v0.3.0

**Comment by chuckha** [comment]
We do have that written up in the README https://github.com/kubernetes-sigs/cluster-api-provider-docker/blob/master/README.md#testing-out-capd

but perhaps it should be listed as a separate section, is that what this issue is getting at?

**Comment by amy** [comment]
Oh! I missed that part. But yeah I think creating a separate section where its harder to overlook that external dependency + version would be good.
