### ISSUE TITLE
Refactor cloud-init module a bit

### ISSUE THREAD

**Issue by chuckha** [kubernetes-sigs/cluster-api-provider-docker#211]
/kind feature
/help
/priority important-longterm
/milestone Next

**Describe the solution you'd like**
cloud-init is very dynamic in what it parses. However, we should take advantage of the fact cloud-init has a defined schema. For now we only care about write_files and runcmd modules. We should explicitly define a type like

```
type cloudconfig struct {
  writeFiles []writefile
  rucmds []runcmd
  unknownModules []unknown
  log logr.Logger
}
```
We can still use the existing custom parsing so we can capture unknown modules and then log them.

**Anything else you would like to add:**

**Environment:**

**Comment by Xenwar** [comment]
Will take this

**Comment by kashifest** [comment]
I am also interested to work on this @Xenwar

**Comment by Xenwar** [comment]
Agreed. Let's start working on it together.
