### ISSUE TITLE
Add image lookup instead of hardcoding image versions for kindest/node

### ISSUE THREAD

**Issue by detiber** [kubernetes-sigs/cluster-api-provider-docker#219]
/kind feature

**Describe the solution you'd like**
Currently we hardcode the available image versions of kindest/node available, we should implement some type of a lookup instead.

**Environment:**

- Cluster-api-provider-docker version: latest

**Comment by fabriziopandini** [comment]
@detiber with  https://github.com/kubernetes-sigs/cluster-api-provider-docker/pull/210 this is changed a little bit and the list of harcoded images was removed (see 
https://github.com/kubernetes-sigs/cluster-api-provider-docker/blob/bc6d722b98e9cb3fed46ba3a21a371075c2c75c2/docker/machine.go#L215)

However, there is not yet lookup logic...

**Comment by Xenwar** [comment]
Considering taking this issue, but would like to know the following. 
- Is `lookup` equivalent to verifying/validating existence of `registry/image:tag`

basically, trying to see the added value of the `lookup` over adding more entry in the cont block, much like the defaultImage

**Comment by detiber** [comment]
@Xenwar yes, a lookup would require either attempting to pull an image based on the version or otherwise querying the registry to ensure the image exists.

**Comment by detiber** [comment]
The added benefit would be that you could take advantage of newer versions without requiring an update to CAPD to update the list of known images.

**Comment by Xenwar** [comment]
Thanks, clear. Will take the issue.
