### ISSUE TITLE
Fix up fmt.Printlns everywhere

### ISSUE THREAD

**Issue by chuckha** [kubernetes-sigs/cluster-api-provider-docker#22]
There are a lot of fmt.Printlns. They should be treated as a logging dependency, as in, for now it's ok to add a parameter to the function that is a logger interface. We have been using `logr.Logger` in a few places, so I think it would be good to continue using that.

/kind enhancement

**Comment by amy** [comment]
Will go ahead and start tackling this.

**Comment by amy** [comment]
There are 2 main sections that have `fmt.Print` that can be separated out. One is within the actuators. The other portion is within `/kind` related files.

**Comment by chuckha** [comment]
I think this is fine too close. there is still some work to do but will be handled by other issues

/close
