### ISSUE TITLE
Delete dockermachine fails if related cluster and machine are deleted first

### ISSUE THREAD

**Issue by detiber** [kubernetes-sigs/cluster-api-provider-docker#221]
/kind bug

**What steps did you take and what happened:**
- created a cluster consisting of a single control plane instance
- issued a delete for the cluster (the dockermachine wasn't cleaned up as part of the delete, bug in capi, I suspect)
- attempt to delete straggling dockermachine

The delete of the dockermachine fails because attempts to get the related Machine and Cluster fail.

**What did you expect to happen:**

The delete of the dockermachine should be able to succeed without having a related Machine or Cluster.

**Environment:**

- capd-manager version (use `kubectl -n docker-provider-system get pods/docker-provider-controller-manager-0 -ojsonpath='{.status.containerStatuses[0].image}{"\n"}{.status.containerStatuses[0].imageID}{"\n"}'`): latest
- Kubernetes version (use `kubectl version`): v1.15.0

**Comment by Xenwar** [comment]
I could not reproduce the issue. 
Could it be that it was fixed indirectly by some other changes in the code ?

**Comment by ashish-amarnath** [comment]
This may be a dup of #222 
https://github.com/kubernetes-sigs/cluster-api-provider-docker/issues/222#issuecomment-535276863

**Comment by Xenwar** [comment]
The code has moved to cluster-api repo, but this repo still accepts bug fixes. 
According to the comments on #222, the issue #222 may no longer be needed as it may have been fixed. And, since #221 is similar, if not identical, to #222, both issues may not be needed any longer. Therefore this issue can be closed.
