### ISSUE TITLE
Make Manager SyncPeriod configurable via a flag

### ISSUE THREAD

**Issue by joonas** [kubernetes-sigs/cluster-api-provider-docker#228]
/kind feature

**Describe the solution you'd like**

It should be possible to configure the [SyncPeriod](https://godoc.org/sigs.k8s.io/controller-runtime/pkg/manager#Options.SyncPeriod) (how often watched resources are re-queued to be reconciled) that’s used to configure the [Manager](https://github.com/kubernetes-sigs/cluster-api-provider-docker/blob/34bb5e31f7a574d94a7e246566f836428d4a4874/main.go#L58-L62) (see [CAPA](https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/12ab064cd2d108ee81e69808dfd23103fbd5dbe6/main.go#L124) for example).

This would be something that should be exposed as a flag (`--sync-period`?) with a reasonable default.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Comment by Xenwar** [comment]
Taking this one, previous worked on https://github.com/kubernetes-sigs/cluster-api/issues/1322

**Comment by Xenwar** [comment]
Could this issue be closed ?

**Comment by detiber** [comment]
Yes
/close
