### ISSUE TITLE
Error running go install ./cmd/capdctl

### ISSUE THREAD

**Issue by sb1975** [kubernetes-sigs/cluster-api-provider-docker#230]
/kind bug
root@capd:~/cluster-api-provider-docker# go install ./cmd/capdctl
can't load package: package sigs.k8s.io/cluster-api-provider-docker/cmd/capdctl: unknown import path "sigs.k8s.io/cluster-api-provider-docker/cmd/capdctl": cannot find package
**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

**What did you expect to happen:**

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- capdctl version (use `capdctl version`):
- capd-manager version (use `kubectl -n docker-provider-system get pods/docker-provider-controller-manager-0 -ojsonpath='{.status.containerStatuses[0].image}{"\n"}{.status.containerStatuses[0].imageID}{"\n"}'`):
- Kubernetes version (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

**Comment by joonas** [comment]
@sb1975 it looks like `capdctl` was removed in https://github.com/kubernetes-sigs/cluster-api-provider-docker/pull/193, but it looks like the [README still references it](https://github.com/kubernetes-sigs/cluster-api-provider-docker#trying-capd). 

Were you trying to use `capdctl` to set up a management cluster to get going with? In that case you may want to look into either [`kind`](https://github.com/kubernetes-sigs/kind) or Docker for X (where is your OS) and running `kustomize build config/default | kubectl apply -f -` against that cluster.

Mind you, you'll also need [CAPI](https://github.com/kubernetes-sigs/cluster-api) and [CABPK](https://github.com/kubernetes-sigs/cluster-api) running in that cluster.
