### ISSUE TITLE
Document how to create/use local images for testing

### ISSUE THREAD

**Issue by pablochacin** [kubernetes-sigs/cluster-api-provider-docker#24]
Presently README explains that for creating local image for the controller the following command can be used:
`docker build -t my-repository/capd-manager:latest . `

In order to use this local image, it must be loaded into the `kind` cluster using `kind` load command:
`kind load docker-image my-custom-image:unique-tag`

However, `kind` documentation warns about not using the `latest` label: 

> The Kubernetes default pull policy is IfNotPresent unless the image tag is :latest in which case the default policy is Always. IfNotPresent causes the Kubelet to skip pulling an image if it already exists. If you want those images loaded into node to work as expected, please:
>
>don’t use a :latest tag

CAPD documentation should include this same instructions and don't suggest using `latest` label. 

/documentation

**Comment by chuckha** [comment]
The alternative here is to upload the image so that it doesn't need to be loaded, but that's pushing the image out only to be pulled locally. It might be a waste of bandwidth but it is easy.

I wonder if there is value in being able to run this offline?

**Comment by chuckha** [comment]
/close

timeout
