### ISSUE TITLE
my-cluster-kubeconfig secret is missing the API server IP address.

### ISSUE THREAD

**Issue by sb1975** [kubernetes-sigs/cluster-api-provider-docker#243]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

I built the cluster API setup using KIND.

# kind create cluster --config ./devenv/kind/config.yaml
Creating cluster "kind" ...
 ✓ Ensuring node image (kindest/node:v1.15.3) 🖼
 ✓ Preparing nodes 📦
 ✓ Creating kubeadm config 📜
 ✓ Starting control-plane 🕹️
 ✓ Installing CNI 🔌
 ✓ Installing StorageClass 💾
Cluster creation complete. You can now use the cluster with:

export KUBECONFIG="$(kind get kubeconfig-path --name="kind")"
kubectl cluster-info
root@capd-2:~/capi-dev# export KUBECONFIG="$(kind get kubeconfig-path --name="kind")"
root@capd-2:~/capi-dev# kubectl cluster-info
Kubernetes master is running at https://127.0.0.1:44377
KubeDNS is running at https://127.0.0.1:44377/api/v1/namespaces/kube-system/services/kube-dns:dns/proxy

root@capd-2:~/capi-dev# kubectl get pods --all-namespaces
NAMESPACE      NAME                                         READY   STATUS    RESTARTS   AGE
cabpk-system   cabpk-controller-manager-676b7d6796-vbrpm    2/2     Running   0          6h6m
capd-system    capd-controller-manager-6d7f8f6f45-7rl2q     2/2     Running   0          6h2m
capi-system    capi-controller-manager-5fc8ffb7b8-2hr2c     1/1     Running   0          6h8m
kube-system    coredns-5c98db65d4-9ht7m                     1/1     Running   0          6h9m
kube-system    coredns-5c98db65d4-bzlgz                     1/1     Running   0          6h9m
kube-system    etcd-kind-control-plane                      1/1     Running   0          6h8m
kube-system    kindnet-8z27d                                1/1     Running   1          6h9m
kube-system    kube-apiserver-kind-control-plane            1/1     Running   0          6h9m
kube-system    kube-controller-manager-kind-control-plane   1/1     Running   0          6h9m
kube-system    kube-proxy-748gv                             1/1     Running   0          6h9m
kube-system    kube-scheduler-kind-control-plane            1/1     Running   0          6h9m

# k get secrets -n tenant-a
NAME                    TYPE                                  DATA   AGE
default-token-hqxf7     kubernetes.io/service-account-token   3      7m31s
my-cluster-ca           Opaque                                2      6m1s
my-cluster-etcd         Opaque                                2      6m1s
my-cluster-kubeconfig   Opaque                                1      6m
my-cluster-proxy        Opaque                                2      6m1s
my-cluster-sa           Opaque                                2      6m1s

# kubectl get secret my-cluster-kubeconfig -n tenant-a -o jsonpath={.data.value} | base64 -d  > kubecfg

[kubecfg.txt](https://github.com/kubernetes-sigs/cluster-api-provider-docker/files/3580228/kubecfg.txt)

**What did you expect to happen:**

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- capdctl version (use `capdctl version`):
- capd-manager version (use `kubectl -n docker-provider-system get pods/docker-provider-controller-manager-0 -ojsonpath='{.status.containerStatuses[0].image}{"\n"}{.status.containerStatuses[0].imageID}{"\n"}'`):
- Kubernetes version (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

**Comment by ashish-amarnath** [comment]
I am unable to repro this bug and here is what I did:

- Following [kind.md](https://github.com/kubernetes-sigs/cluster-api-provider-docker/blob/master/docs/kind.md) created a management cluster and setup `KUBECONFIG` to point to this cluster
- Deployed capi components as 
```
# from capi repo master HEAD b0e9d37385f9c93c4422b74fb3c0f456637188a0
$ kustomize build config/default | kc apply -f -
```
- Deployed cabpk  components as 
```
# from cabpk repo master HEAD 7b907ab78b8c28d62382e9f52148a72543de3cef
$ kustomize build config/default | kc apply -f -
```
- Built the capd manager image from capd repo master HEAD `8dc38744ec024354643d926372a135a516fbba79` as  `quay.io/ashish_amarnath/manager:dev-0925201900` (Please don't deploy this image in sensitive environments)
- Deployed capd components as
```
# from capd repo master HEAD at `8dc38744ec024354643d926372a135a516fbba79`
$ git diff
diff --git a/config/default/manager_image_patch.yaml b/config/default/manager_image_patch.yaml
index 6cf5307..bb5260e 100644
--- a/config/default/manager_image_patch.yaml
+++ b/config/default/manager_image_patch.yaml
@@ -8,5 +8,5 @@ spec:
     spec:
       containers:
       # Change the value of image field below to your controller image URL
-      - image: gcr.io/kubernetes1-226021/manager:dev
+      - image: quay.io/ashish_amarnath/manager:dev-0925201900
         name: manager
$ kustomize build ./config/default/ | kc apply -f -
```
- Confirm all  provider controllers are running
- Create a capd cluster from [cmd/testdata/default-capd-no-machine-deployment.golden](https://github.com/ashish-amarnath/capi-yaml-gen/blob/master/cmd/testdata/default-capd-no-machine-deployment.golden)
- Wait for it to be reconciled
- Get `my-cluster`'s kubeconfig secret from management cluster and confirm `server` is populated as expected
```
$ kc get secret my-cluster-kubeconfig -ojsonpath={.data.value} | base64 -d | grep server
    server: https://172.17.0.3:6443
```
- Use the kubeconfig to talk to the newly reconciled cluster
```
$ kc cluster-info
Kubernetes master is running at https://172.17.0.3:6443
KubeDNS is running at https://172.17.0.3:6443/api/v1/namespaces/kube-system/services/kube-dns:dns/proxy
$ kc version
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.1", GitCommit:"4485c6f18cee9a5d3c3b4e523bd27972b1b53892", GitTreeState:"clean", BuildDate:"2019-07-18T09:18:22Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.4", GitCommit:"67d2fcf276fcd9cf743ad4be9a9ef5828adc082f", GitTreeState:"clean", BuildDate:"2019-09-18T14:41:55Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
```

@sb1975  can you please confirm if these are the same steps you followed?

**Comment by chuckha** [comment]
no response. Due to issue migration please reopen in github.com/kubernetes-sigs/cluster-api if still applicable.

/close
