### ISSUE TITLE
Remove `kind` as a dependency

### ISSUE THREAD

**Issue by chuckha** [kubernetes-sigs/cluster-api-provider-docker#246]
/kind feature
/priority longterm-important
/milestone Next

**Describe the solution you'd like**
I'd like to remove kind (the library) as a dependency. From talking with some of the kind folk it sounds like it's not really meant to be used so we should extract ourselves as quickly as possible. 

It should not be too bad to use some container client to spin up nodes instead of relying on kind.

**Comment by chuckha** [comment]
The general direction I'd like to see here is to have a docker client that either uses a go library or wraps docker exec and gets passed to the reconciler. That will let us fake it for tests and remove the kind library calls.

**Comment by chuckha** [comment]
@kfox1111 This repo is deprecated. I've tagged you in the relevant issue over in the cluster-api repository. If you have time to work on this it would be really awesome.

https://github.com/kubernetes-sigs/cluster-api/issues/1751

**Comment by kfox1111** [comment]
Thanks for the update. Unfortunately, my list of projects needing attention is already very long. Sorry. If my time frees up I'll ping you though.
