### ISSUE TITLE
External cloud provider docker

### ISSUE THREAD

**Issue by chuckha** [kubernetes-sigs/cluster-api-provider-docker#250]
/kind feature
/priority important-soon
/milestone v0.3.0

**Describe the solution you'd like**
In order to have parity with other cloud providers we should add a docker cloud provider.

This cloud provider would be responsible for things like

* Creating load balancers for Services with type = LoadBalancer
* Assign ProviderID to the node/machine
* ?

cc @dlipovetsky 

**Anything else you would like to add:**
Not really sure how this will integrate with kubeadm, probably with --cloud-provider=external, but what other configuration do we need to supply?

**Comment by chuckha** [comment]
cc @joonas

**Comment by dlipovetsky** [comment]
/close

This repo is deprecated. If this is needed in the future, I'll open an issue on cluster-api, where CAPD moved to.
