### ISSUE TITLE
CAPI quick start docs does not bring up a worker cluster

### ISSUE THREAD

**Issue by tamalsaha** [kubernetes-sigs/cluster-api-provider-docker#259]
/kind bug

**What steps did you take and what happened:**
I followed the steps here:
https://github.com/kubernetes-sigs/cluster-api/blob/master/docs/book/src/user/quick-start.md

The cluster did not come up.
I see the following error is capd-docker logs

```
$ kubectl logs -f -n capd-system -c manager capd-controller-manager-8594dfd47d-ffcgb

I0314 12:30:31.296597       1 machine.go:333] controllers/DockerMachine/DockerMachine-controller "msg"="Setting Kubernetes node providerID" "cluster"="capi-quickstart" "docker-cluster"="capi-quickstart" "docker-machine"={"Namespace":"default","Name":"capi-quickstart-control-plane-lvcf9"} "machine"="capi-quickstart-control-plane-7qdd9" 
I0314 12:30:31.538455       1 machine.go:345] controllers/DockerMachine/DockerMachine-controller "msg"="Unable to connect to the server: x509: certificate signed by unknown authority (possibly because of \"crypto/rsa: verification error\" while trying to verify candidate authority certificate \"kubernetes\")" "cluster"="capi-quickstart" "docker-cluster"="capi-quickstart" "docker-machine"={"Namespace":"default","Name":"capi-quickstart-control-plane-lvcf9"} "machine"="capi-quickstart-control-plane-7qdd9" 
E0314 12:30:31.538541       1 dockermachine_controller.go:324] controllers/DockerMachine "msg"="failed to patch the Kubernetes node with the machine providerID" "error"="failed update providerID: command \"docker exec --privileged capi-quickstart-control-plane-79qxs kubectl --kubeconfig /etc/kubernetes/admin.conf patch node capi-quickstart-control-plane-7qdd9 --patch '{\"spec\": {\"providerID\": \"docker:////capi-quickstart-control-plane-7qdd9\"}}'\" failed with error: exit status 1"  
```

**What did you expect to happen:**
I expected the worker cluster to be ready.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- capd-manager version (use `kubectl -n docker-provider-system get pods/docker-provider-controller-manager-0 -ojsonpath='{.status.containerStatuses[0].image}{"\n"}{.status.containerStatuses[0].imageID}{"\n"}'`):

    image: gcr.io/k8s-staging-cluster-api/capd-manager:v0.3.14
    imageID: gcr.io/k8s-staging-cluster-api/capd-manager@sha256:6811a31541b3af999bed4c0643a3b3155483b0fc1744abd635bb00a7d26556c5

- Kubernetes version (use `kubectl version`):

Client Version: v1.20.4
Server Version: v1.19.7

- OS (e.g. from `/etc/os-release`):
Ubuntu 18.04

**Comment by fabriziopandini** [comment]
FYI this repository has been discontinued more than year ago, and now CAPD is hosted at https://github.com/kubernetes-sigs/cluster-api/. Please move the issue there.
/close
