### ISSUE TITLE
Set up automated tests

### ISSUE THREAD

**Issue by chuckha** [kubernetes-sigs/cluster-api-provider-docker#5]
Get the prow configuration in place so we can run tests on PRs. I don't think we need periodics yet, just PR jobs.

**Comment by ashish-amarnath** [comment]
waiting on https://github.com/kubernetes-sigs/cluster-api-provider-docker/pull/13

**Comment by ashish-amarnath** [comment]
Hints: https://github.com/kubernetes/test-infra/tree/0fabd2ea816daa8c15d410c77a0c93c0550b283f/config/jobs/kubernetes-sigs/cluster-api-provider-aws

**Comment by neolit123** [comment]
https://github.com/kubernetes/test-infra/blob/master/config/jobs/kubernetes/kubeadm/kubeadm-presubmits.yaml

is the best example, just call `verify-all.sh`.

**Comment by neolit123** [comment]
will update #13 later today.

**Comment by neolit123** [comment]
/remove help
given multiple people are helping here already.

**Comment by chuckha** [comment]
unblocked!! 🎉

**Comment by neolit123** [comment]
/priority important-soon

@ashish-amarnath 
i took the liberty of sending a PR for this as there are a lot of cleanup PRs that we are not catching for errors:
https://github.com/kubernetes/test-infra/pull/13175

**Comment by neolit123** [comment]
https://github.com/kubernetes/test-infra/pull/13175
merged

status on unmerged PRs is showing `pull-cluster-api-provider-docker-verify Expected — Waiting for status to be reported`. no idea why, but prow is having issues recently. also the dashboard for 
provider-docker has not appeared yet https://k8s-testgrid.appspot.com/sig-cluster-lifecycle-all

**Comment by neolit123** [comment]
i'm assuming that now a PR blocking e2e is needed, such that creates a full cluster using the provider?

**Comment by ashish-amarnath** [comment]
sorry for the delay on this :( and thanks for picking it up for me.

**Comment by chuckha** [comment]
@ashish-amarnath is there any more work to be done for this? I think we can close it out.

**Comment by ashish-amarnath** [comment]
Yes, we can close it out.
/close
