### ISSUE TITLE
Support both v1a1 and v1a2 of cluster api

### ISSUE THREAD

**Issue by chuckha** [kubernetes-sigs/cluster-api-provider-docker#54]
/kind feature

We want to test out v1alpha2 with this provider, but we will also have to support v1alpha1 as well

**Comment by detiber** [comment]
I hate to say it, but the easiest approach here might just be to branch.

**Comment by chuckha** [comment]
can you elaborate? I'd like to use this space to understand what actually has to be done for this issue and haven't had time to get started yet

**Comment by ncdc** [comment]
Agreed - let's see what we can/can't accomplish.

Also @chuckha do you anticipate that this provider will be able to use the kubeadm bootstrapper when it's available to generate bootstrap data? That will require being able to pass the data in to the containers & have them use it.

**Comment by chuckha** [comment]
/assign
/lifecycle active

related to #67

**Comment by chuckha** [comment]
release branch now exists. We are supporting both! 🎉 
/close
