### ISSUE TITLE
cluster api v0.1.4 doesn't work with current implementation

### ISSUE THREAD

**Issue by chuckha** [kubernetes-sigs/cluster-api-provider-docker#55]
/kind bug

The main problem lies in the fact that the cluster api node ref controller, running in the management cluster (kind) doesn't share the network with the load balancer.

For this to work cluster API network must have access to the child cluster's network.

**Comment by chuckha** [comment]
I think one thing we can do here is to run the management cluster not in KIND but as its own cluster(just a control plane node). 

I'm trying to figure out why i didn't start this way...

**Comment by ashish-amarnath** [comment]
Can you elaborate on why the node ref controller needs to have access to the child cluster's n/w?
I also need to read the node ref controller code.

**Comment by ashish-amarnath** [comment]
never mind.. I read the node ref controller code and got what you were saying. The nesting that we are doing here.. I need to always step back and think _carefully_ which container are we in again 😂

**Comment by chuckha** [comment]
I think the move is to get away from `kind create cluster` for the management cluster and just spin up a control plane node. Overall this will be a good thing (fewer resources) but....this requires that kind exposes some things it doesn't yet expose so we will be diverging from kind even further. I am glad of the name I chose TBH.
