### ISSUE TITLE
make 6443 a constant

### ISSUE THREAD

**Issue by chuckha** [kubernetes-sigs/cluster-api-provider-docker#66]
We hardcode 6443 all over the place and it should be a constant

/kind enhancement

**Comment by SharksZhang** [comment]
I am a new contributor, could you please tell me more information about this issue. @chuckha

**Comment by chuckha** [comment]
@SharksZhang Sure! We are hardcoding 6443 in a few places across the codebase. 

We should make a package called "constants" and define constants in there. Here are some examples of hard coded 6443:

https://github.com/kubernetes-sigs/cluster-api-provider-docker/blob/master/kind/actions/kind.go#L249
https://github.com/kubernetes-sigs/cluster-api-provider-docker/blob/master/kind/actions/cluster_actions.go#L102
https://github.com/kubernetes-sigs/cluster-api-provider-docker/blob/master/kind/kubeadm/config.go#L55

and several others.

Thanks for looking into this!
