### ISSUE TITLE
Improve dev-builds

### ISSUE THREAD

**Issue by chuckha** [kubernetes-sigs/cluster-api-provider-docker#98]
/kind feature

**Describe the solution you'd like**
Builds are now optimized towards releasing and not dev.

In order to make the dev workflow experience better we should create a makefile that builds docker-images and builds binaries with version embedded

This issue is a result of changing the release pipeline.

**Comment by ashish-amarnath** [comment]
Ref: https://github.com/kubernetes-sigs/cluster-api-provider-docker/pull/95/files#r306340239
